# relative to current dir
# for absolute use '/'
db_file: 'data/db.sqlite'

# number of concurrent tasks to run
concurrent_tasks: 1

# interval between task status check seconds
task_check_interval: 10

# task output file pattern
output_pattern: 'data/tasks/%s.output'

tasks:
  - name: 'list_files'
    cmd: 'ls -la'
    base_dir: /home/
  - name: 'list_dir'
    cmd: 'ls {dir_name}'
